### ISSUE TITLE
Incorrect DNS

### ISSUE THREAD

**Issue by aburgel** [django-nonrel/django-nonrel.github.com#2]
@jonashaag, i see that you added the CNAME file for django-nonrel.org, but the dns is not configured properly.

The A record needs to point to 204.232.175.78

https://help.github.com/articles/setting-up-a-custom-domain-with-pages

**Comment by aburgel** [comment]
@jonashaag, have you been able to look into this? the domain is still pointing to the wrong IP

**Comment by jonashaag** [comment]
Oups, forgot about this issue. A records should be fixed with the next DNS update

EDIT: actually it works immediately, at least for me. seems like you don't do DNS caching these days?!

**Comment by aburgel** [comment]
Works for me too. Thanks!
